services:
  - type: web
    name: taskbot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SECRET_PATH
        generateValue: true
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: taskbot
          property: host
